---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: dhakerkarous
    password: machete12
    email: karousdhaker@gmail.com
    
#----------------------------------------    

- name: Tag and push to docker hub
  docker_image:
    name: devops
    source: build
    build: 
    	path: /var/lib/jenkins/workspace/CD
    repository: dhakerkarous/devops
    tag: latest
    push: yes
